name: pyhf-pymc
channels:
  - conda-forge
dependencies:
  - python=3.11
  # project core
  - pyhf==0.7.0
  - jax==0.4.2
  - jaxlib==0.4.2
  # use '=' to minor version as different conda-forge releases across platforms
  - pymc=5.0
  - blackjax==0.9.6
  - corner==2.2.1
  # jupyter
  - notebook>=6.5.2
  # use '>=' as different conda-forge releases across platforms
  - jupyterlab>=3.5.3
  - ipympl==0.9.2
  - jupytext==1.14.4
  - pip>=23.0
  - aesara=2.8.12
  - pyhf_pymc=0.0.1
# nonstandard, but used by conda-lock
platforms:
  - linux-64
  - osx-arm64